# File: .github/actions/read-trains-json/action.yml

name: 'Read Trains JSON'
description: 'Reads trains.json and outputs environments for the selected train'
inputs:
  train:
    description: 'The selected train'
    required: true
outputs:
  environments:
    description: 'Environments for the selected train'
    value: ${{ steps.read-trains.outputs.environments }}
runs:
  using: 'composite'
  steps:
    - name: Read Trains JSON
      id: read-trains
      shell: bash
      run: |
        echo "Selected train: ${{ inputs.train }}"
        cat "$GITHUB_ACTION_PATH/trains.json"
        envs=$(jq -c --arg TRAIN "${{ inputs.train }}" '.[$TRAIN]' "$GITHUB_ACTION_PATH/trains.json")
        if [ -z "$envs" ] || [ "$envs" == "null" ]; then
          echo "Error: Train '${{ inputs.train }}' not found in trains.json"
          exit 1
        fi
        echo "environments=$envs" >> "$GITHUB_STEP_OUTPUT"
