name: 'Read Trains YAML'
description: 'Reads trains.yaml and outputs environments for the selected train'
inputs:
  train:
    description: 'The selected train'
    required: true
  PAT_TOKEN:
    description: 'Personal Access Token for repository access'
    required: true
outputs:
  environments:
    description: 'Environments for the selected train'
    value: ${{ steps.read-trains.outputs.environments }}
runs:
  using: 'composite'
  steps:
    - name: Install yq
      shell: bash
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Checkout metadata repository
      uses: actions/checkout@v3
      with:
        repository: topaco/metadata
        path: metadata
        ref: main
        token: ${{ inputs.PAT_TOKEN }} # Use the input for the token

    - name: Read Trains YAML
      id: read-trains
      shell: bash
      env:
        TRAIN: ${{ inputs.train }}
      run: |
        echo "Selected train: ${{ inputs.train }}"
        envs=$(yq eval -o=json ".\"$TRAIN\"" "metadata/v1/trains.yaml" | jq -c .)
        echo "Parsed environments: $envs"
        if [ -z "$envs" ] || [ "$envs" == "null" ]; then
          echo "Error: Train '${{ inputs.train }}' not found in trains.yaml"
          exit 1
        fi
        echo "environments=$envs" >> "$GITHUB_OUTPUT"



