name: Deploy to Environment

on:
  workflow_call:
    inputs:
      serviceName:
        description: 'Name of the service to deploy'
        required: true
        type: string
      operation:
        description: 'Operation to perform'
        required: true
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  terraform:
    uses: topaco/multi_env/.github/workflows/deploy.yaml@main
    with:
      serviceName: test-java-service
      operation: deploy
      environment: ${{ inputs.environment }}
    secrets:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  helm:
    needs: terraform
    uses: topaco/multi_env/.github/workflows/deploy.yaml@main
    with:
      serviceName: test-java-service
      operation: deploy
      environment: ${{ inputs.environment }}
      #certificate_arn: ${{ needs.terraform.outputs.certificate_arn }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
