name: github context

on: workflow_dispatch

jobs:
  github_cont:
    runs-on: ubuntu-latest

    steps:
    - name: Echo GitHub context
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Repository Owner: ${{ github.repository_owner }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Workflow Name: ${{ github.workflow }}"
        echo "Action: ${{ github.action }}"
        echo "Actor: ${{ github.actor }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Run Number: ${{ github.run_number }}"
