name: Train Deployment

on:
  workflow_dispatch:
    inputs:
      train:
        description: 'Select the deployment train'
        required: true
        default: default
        type: choice
        options:
          - default
          - Sandbox01
          - Sandbox02
          - small_env

jobs:
  prepare:
    name: Prepare Environments List
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.get-envs.outputs.environments }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Trains JSON
        id: get-envs
        uses: ./.github/actions/read-trains-json
        with:
          train: ${{ github.event.inputs.train }}

  deploy:
    name: Deploy Environments
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Debug Outputs
        run: |
          echo "Environments from prepare job: '${{ needs.prepare.outputs.environments }}'"

      - name: Deploy to Environments
        shell: bash
        run: |
          echo "Environments to deploy: ${{ needs.prepare.outputs.environments }}"
          envs='${{ needs.prepare.outputs.environments }}'
          if [ -z "$envs" ] || [ "$envs" == "null" ]; then
            echo "No environments to deploy."
            exit 1
          fi
          for env in $(echo "$envs" | jq -r '.[]'); do
            echo "Deploying to $env environment"
            # Add your deployment commands here
          done
