name: Train Deployment

on:
  workflow_dispatch:
    inputs:
      start_environment:
        type: choice
        description: 'Select the starting environment for deployment train'
        options:
          - dev
          - test
          - non-prod
          - prod
        default: dev

env:
  SERVICE_NAME: shop-cep-service
  OPERATION: deploy

jobs:
  deploy_dev:
    if: ${{ inputs.start_environment == 'dev' || inputs.start_environment == 'test' || inputs.start_environment == 'non-prod' || inputs.start_environment == 'prod' }}
    name: Deploy to Dev
    uses: VF-DigitalEngineering-CloudEngineering/cep-actions-hub/.github/workflows/helm.yaml@main
    with:
      serviceName: ${{ env.SERVICE_NAME }}
      operation: ${{ env.OPERATION }}
      environment: dev
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  deploy_test:
    if: ${{ inputs.start_environment == 'test' || inputs.start_environment == 'non-prod' || inputs.start_environment == 'prod' }}
    needs: deploy_dev
    name: Deploy to Test
    uses: VF-DigitalEngineering-CloudEngineering/cep-actions-hub/.github/workflows/helm.yaml@main
    with:
      serviceName: ${{ env.SERVICE_NAME }}
      operation: ${{ env.OPERATION }}
      environment: test
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  deploy_non_prod:
    if: ${{ inputs.start_environment == 'non-prod' || inputs.start_environment == 'prod' }}
    needs: deploy_test
    name: Deploy to Non-Prod
    uses: VF-DigitalEngineering-CloudEngineering/cep-actions-hub/.github/workflows/helm.yaml@main
    with:
      serviceName: ${{ env.SERVICE_NAME }}
      operation: ${{ env.OPERATION }}
      environment: non-prod
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  deploy_prod:
    if: ${{ inputs.start_environment == 'prod' }}
    needs: deploy_non_prod
    name: Deploy to Prod
    environment:
      name: prod
      url: https://your-production-url.com
      protection_rules:
        required_reviewers:
          - your-github-username
    uses: VF-DigitalEngineering-CloudEngineering/cep-actions-hub/.github/workflows/helm.yaml@main
    with:
      serviceName: ${{ env.SERVICE_NAME }}
      operation: ${{ env.OPERATION }}
      environment: prod
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
