name: Train Deployment

on:
  workflow_dispatch:
    inputs:
      train:
        description: 'Select the deployment train'
        required: true
        default: default
        type: choice
        options:
          - default
          - Sandbox01
          - Sandbox02
          - small_env

jobs:
  prepare:
    name: Prepare Environments List
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.prepare.outputs.environments }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Trains JSON
        id: prepare
        uses: ./.github/actions/read-trains-json
        with:
          train: ${{ github.event.inputs.train }}

  deploy:
    name: Deploy Environments
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Environments
        shell: bash
        run: |
          echo "Environments to deploy: ${{ needs.prepare.outputs.environments }}"
          envs=${{ needs.prepare.outputs.environments }}
          for env in $(echo $envs | jq -r '.[]'); do
            echo "Deploying to $env environment"
            # Add your deployment commands here
          done
