name: deploy

on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: 'Name of the service to deploy'
        required: true
        type: string
      train:
        description: 'Select the train for deployment'
        required: true
        type: choice
        options:
          - default
          - Sandbox01
          - Sandbox02
          - small_env

jobs:
  prepare:
    name: Prepare Environments List
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.get-envs.outputs.environments }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Trains YAML
        id: get-envs
        uses: topaco/multi_env/.github/actions/read_train@main
        with:
          train: ${{ github.event.inputs.train }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }} # Pass the PAT_TOKEN as an input

      - name: Debug Prepared Environments
        run: |
          echo "Prepared environments: ${{ steps.get-envs.outputs.environments }}"

  ReuseableMatrixJobForDeployment:
    needs: prepare
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.environments) }}
    uses: topaco/multi_env/.github/workflows/deploy_env.yaml@main
    with:
      serviceName: ${{ github.event.inputs.serviceName }}
      environment: ${{ matrix.target }}
      operation: deploy
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
